name: Python packaging with Poetry

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-and-publish-package:
    runs-on: ubuntu-20.04
    environment: publish
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Load cached Poetry installation
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-0
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install
      - name: Build package
        run: poetry build
      - name: Publish package distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Create release
        uses: softprops/action-gh-release@v1